name       : perl-dbd-sqlite
version    : 1.62
release    : 7
source     :
    - https://search.cpan.org/CPAN/authors/id/I/IS/ISHIGAKI/DBD-SQLite-1.62.tar.gz : bd82ef322a9e5469a7a62d845c32fad1188b76ccb49a88520cec768343cce85c
license    :
    - Artistic-1.0
    - GPL-2.0-or-later
component  : programming.perl
summary    : Self-contained RDBMS in a DBI Driver
description: |
    DBD::SQLite is a Perl DBI driver for SQLite, that includes the entire thing in the distribution. So in order to get a fast transaction capable RDBMS working for your perl project you simply have to install this module, and nothing else.
builddeps  :
    - perl-dbi
rundeps    :
    - perl-dbi
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %make test
